# Generated by Django 4.2.1 on 2023-05-23 13:55

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth2ClientCredentials',
            fields=[
                ('client_id', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=100)),
                ('authorisation_id', models.AutoField(help_text='authorisation_id,access_token', primary_key=True, serialize=False)),
                ('webhook_key', models.CharField(max_length=100)),
                ('callback_uri', models.CharField(max_length=150)),
                ('cred_state', jsonfield.fields.JSONField(blank=True, null=True)),
                ('environment', models.CharField(blank=True, default='sandbox', help_text='quickbooks_env', max_length=100, null=True)),
            ],
        ),
    ]
