# Generated by Django 4.1 on 2022-09-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_authorization', '0002_oauth2clientcredentials_environment_and_more'),
        ('efris', '0004_alter_efriscommoditycategories_tax_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickbooksEfrisClientCredentials',
            fields=[
                ('oauth2clientcredentials_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='client_authorization.oauth2clientcredentials')),
                ('clientcredentials_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='efris.clientcredentials')),
                ('quick_books_id', models.AutoField(help_text='quickbooks api auto id', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': ' Efris Client Credentials',
                'verbose_name_plural': 'Efris Client Credentials',
            },
            bases=('efris.clientcredentials', 'client_authorization.oauth2clientcredentials'),
        ),
    ]
