# Generated by Django 4.2.1 on 2023-06-13 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_efris', '0002_efrisoutgoinginvoice'),
        ('api_dear', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DearOutgoingInvoice',
            fields=[
                ('efrisoutgoinginvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager_efris.efrisoutgoinginvoice')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('manager_efris.efrisoutgoinginvoice',),
        ),
        migrations.CreateModel(
            name='DearEfrisGoodsConfiguration',
            fields=[
                ('efrisgoodsconfiguration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager_efris.efrisgoodsconfiguration')),
                ('client_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_dear.dearcredentials')),
            ],
            options={
                'verbose_name': 'Goods Configuration',
                'verbose_name_plural': 'Goods Configuration',
            },
            bases=('manager_efris.efrisgoodsconfiguration',),
        ),
        migrations.CreateModel(
            name='DearEfrisGoodsAdjustment',
            fields=[
                ('efrisgoodsadjustment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager_efris.efrisgoodsadjustment')),
                ('good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_dear.dearefrisgoodsconfiguration')),
            ],
            options={
                'verbose_name': 'Goods Adjustment',
                'verbose_name_plural': 'Goods Adjustment',
            },
            bases=('manager_efris.efrisgoodsadjustment',),
        ),
        migrations.CreateModel(
            name='DearEfrisClientCredentials',
            fields=[
                ('clientcredentials_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager_efris.clientcredentials')),
                ('dear_account_id', models.CharField(default='39efa556-8dda-4c81-83d3-a631e59eb6d3', max_length=255)),
                ('dear_app_key', models.CharField(default='NONE', max_length=10)),
                ('dear_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_dear.dearcredentials')),
            ],
            options={
                'verbose_name': 'Client Credentials',
                'verbose_name_plural': 'Client Credentials',
            },
            bases=('manager_efris.clientcredentials',),
        ),
    ]
