# Generated by Django 4.2.1 on 2023-06-13 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_dear', '0002_dearoutgoinginvoice_dearefrisgoodsconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dearcredentials',
            name='dear_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dearefrisclientcredentials',
            name='dear_app_key',
            field=models.CharField(default='NONE', max_length=150),
        ),
        migrations.AlterField(
            model_name='dearefrisgoodsconfiguration',
            name='client_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_dear.dearefrisclientcredentials'),
        ),
    ]
