# Generated by Django 4.2.1 on 2023-06-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_dear', '0004_dearefrisclientcredentials_dear_buyer_type_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dearefrisclientcredentials',
            name='dear_stock_commodity_category_field',
            field=models.CharField(default='NONE', max_length=150),
        ),
        migrations.AddField(
            model_name='dearefrisclientcredentials',
            name='dear_stock_currency_field',
            field=models.CharField(default='NONE', max_length=150),
        ),
        migrations.AddField(
            model_name='dearefrisclientcredentials',
            name='dear_stock_description_field',
            field=models.CharField(default='NONE', max_length=150),
        ),
        migrations.AddField(
            model_name='dearefrisclientcredentials',
            name='dear_stock_in_price_field',
            field=models.CharField(default='NONE', max_length=150),
        ),
        migrations.AddField(
            model_name='dearefrisclientcredentials',
            name='dear_stock_measure_unit_field',
            field=models.CharField(default='NONE', max_length=150),
        ),
    ]
