# Generated by Django 4.2.1 on 2023-06-13 08:34

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EfrisInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField()),
                ('client_id', models.CharField()),
                ('mita_request_data', jsonfield.fields.JSONField()),
                ('mita_response_data', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField()),
                ('item_code', models.CharField()),
                ('item_name', models.CharField()),
                ('track_item_qty', models.CharField()),
                ('is_purchased', models.CharField()),
                ('cost_price', models.CharField()),
                ('purchase_account', models.CharField()),
                ('purchase_tax_rate', models.CharField()),
                ('is_sold', models.CharField()),
                ('sale_price', models.CharField()),
                ('sale_account', models.CharField()),
                ('sale_tax_rate', models.CharField()),
                ('description', models.CharField()),
            ],
        ),
    ]
