# Generated by Django 4.2.2 on 2023-07-08 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager_efris', '0002_efrisoutgoinginvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='OECredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oe_url', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ordereasy Credentials',
                'verbose_name_plural': 'Ordereasy Credentials',
            },
        ),
        migrations.CreateModel(
            name='OEEfrisClientCredentials',
            fields=[
                ('clientcredentials_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager_efris.clientcredentials')),
                ('oe_api_key', models.CharField(max_length=500)),
                ('oe_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_ordereasy.oecredentials')),
            ],
            options={
                'verbose_name': 'Client Credentials',
                'verbose_name_plural': 'Client Credentials',
            },
            bases=('manager_efris.clientcredentials',),
        ),
        migrations.CreateModel(
            name='OEOutgoingInvoice',
            fields=[
                ('efrisoutgoinginvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager_efris.efrisoutgoinginvoice')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('manager_efris.efrisoutgoinginvoice',),
        ),
        migrations.CreateModel(
            name='OEEfrisGoodsConfiguration',
            fields=[
                ('efrisgoodsconfiguration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager_efris.efrisgoodsconfiguration')),
                ('client_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_ordereasy.oeefrisclientcredentials')),
            ],
            options={
                'verbose_name': 'Goods Configuration',
                'verbose_name_plural': 'Goods Configuration',
            },
            bases=('manager_efris.efrisgoodsconfiguration',),
        ),
        migrations.CreateModel(
            name='OEEfrisGoodsAdjustment',
            fields=[
                ('efrisgoodsadjustment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager_efris.efrisgoodsadjustment')),
                ('good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_ordereasy.oeefrisclientcredentials')),
            ],
            options={
                'verbose_name': 'Goods Adjustment',
                'verbose_name_plural': 'Goods Adjustment',
            },
            bases=('manager_efris.efrisgoodsadjustment',),
        ),
    ]
