# Generated by Django 4.2.2 on 2023-07-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ordereasy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeefrisclientcredentials',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oeefrisclientcredentials',
            name='oe_url',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='OECredentials',
        ),
    ]
