# Generated by Django 4.1 on 2022-09-26 18:24

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth2ClientCredentials',
            fields=[
                ('authorisation_id', models.AutoField(primary_key=True, serialize=False)),
                ('webhook_key', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=100)),
                ('callback_uri', models.CharField(max_length=150)),
                ('cred_state', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
