# Generated by Django 4.1 on 2022-09-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2clientcredentials',
            name='environment',
            field=models.CharField(blank=True, default='sandbox', help_text='quickbooks_env', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='oauth2clientcredentials',
            name='authorisation_id',
            field=models.AutoField(help_text='authorisation_id,access_token', primary_key=True, serialize=False),
        ),
    ]
