# Generated by Django 4.2.1 on 2023-05-23 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('tax_pin', models.CharField(max_length=30)),
                ('mita_api_header', models.CharField(max_length=150)),
                ('mita_country_code', models.CharField(choices=[('UG', 'UG'), ('ZM', 'ZM'), ('BN', 'BN')], default='UG', max_length=10)),
            ],
            options={
                'verbose_name': 'Mita credentials',
                'verbose_name_plural': 'Mita credentials',
            },
        ),
        migrations.CreateModel(
            name='EfrisCommodityCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efris_commodity_category_name', models.CharField(help_text='Efris Commodity Category', max_length=20)),
                ('efris_commodity_category_code', models.CharField(help_text='Efris Commodity Category Code', max_length=20)),
                ('tax_rate', models.FloatField(choices=[(0.0, 'EXEMPT'), (0.18, 'STANDARD')], default=0.18, help_text='Currency Rate', max_length=10)),
            ],
            options={
                'verbose_name': 'Commodity Category',
                'verbose_name_plural': 'Commodity Categories',
            },
        ),
        migrations.CreateModel(
            name='EfrisCurrencyCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(help_text='Currency Name', max_length=20)),
                ('currency_code', models.CharField(help_text='Currency Code', max_length=20)),
                ('currency_abbr', models.CharField(help_text='Currency Abbr', max_length=20)),
            ],
            options={
                'verbose_name': 'Currency Code',
                'verbose_name_plural': 'Currency Codes',
            },
        ),
        migrations.CreateModel(
            name='EfrisMeasureUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_unit_name', models.CharField(help_text='Measure Unit Name', max_length=20)),
                ('measure_unit_code', models.CharField(help_text='Measure Unit Code', max_length=20)),
                ('measure_unit_abbr', models.CharField(blank=True, help_text='Measure Unit Abbr', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Measure Unit',
                'verbose_name_plural': 'Measure Units',
            },
        ),
        migrations.CreateModel(
            name='EfrisGoodsConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(help_text='Goods Name', max_length=200)),
                ('goods_code', models.CharField(help_text='Goods Code', max_length=200)),
                ('unit_price', models.FloatField(help_text='Unit Price')),
                ('description', models.TextField(help_text='Description')),
                ('commodity_tax_category', models.ForeignKey(help_text='Efris Commodity Category', on_delete=django.db.models.deletion.CASCADE, to='manager_efris.efriscommoditycategories')),
                ('currency', models.ForeignKey(help_text='Currency', on_delete=django.db.models.deletion.CASCADE, to='manager_efris.efriscurrencycodes')),
                ('measure_unit', models.ForeignKey(help_text='Measure Unit', on_delete=django.db.models.deletion.CASCADE, to='manager_efris.efrismeasureunits')),
            ],
            options={
                'verbose_name': ' Efris Goods Configuration',
                'verbose_name_plural': ' Efris Goods Configuration',
            },
        ),
        migrations.CreateModel(
            name='EfrisGoodsAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.FloatField(help_text='Purchase Price')),
                ('supplier', models.CharField(blank=True, help_text='Supplier', max_length=200, null=True)),
                ('supplier_tin', models.CharField(blank=True, help_text='Supplier Tin', max_length=20, null=True)),
                ('quantity', models.CharField(help_text='Quantity', max_length=20)),
                ('stock_in_type', models.CharField(blank=True, choices=[('', 'NONE'), ('101', 'IMPORT'), ('102', 'LPO'), ('103', 'MANUFACTURING/ASSEMBLY'), ('104', 'OPENING STOCK')], default='101', max_length=10, null=True)),
                ('adjust_type', models.CharField(blank=True, choices=[('', 'NONE'), ('101', 'EXPIRED'), ('102', 'DAMAGED'), ('104', 'OTHERS'), ('103', 'PERSONAL USES'), ('105', 'RAW MATERIALS')], default='', max_length=10, null=True)),
                ('operation_type', models.CharField(choices=[('101', 'INCREASE INVENTORY'), ('102', 'DECREASE INVENTORY')], default='', max_length=10)),
                ('purchase_remarks', models.TextField(help_text='Purchase Remarks')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_efris.efriscurrencycodes')),
            ],
            options={
                'verbose_name': 'Goods Stock In',
                'verbose_name_plural': 'Goods Stock In',
            },
        ),
    ]
