# Generated by Django 4.2.1 on 2023-06-13 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_invoice', '0001_initial'),
        ('manager_efris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfrisOutgoingInvoice',
            fields=[
                ('outgoinginvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager_invoice.outgoinginvoice')),
            ],
            bases=('manager_invoice.outgoinginvoice',),
        ),
    ]
