# Generated by Django 4.2.1 on 2023-05-24 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth2', '0001_initial'),
        ('manager_efris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickbooksEfrisClientCredentials',
            fields=[
                ('oauth2clientcredentials_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='oauth2.oauth2clientcredentials')),
                ('clientcredentials_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='manager_efris.clientcredentials')),
                ('quick_books_id', models.AutoField(help_text='quickbooks api auto id', primary_key=True, serialize=False)),
                ('access_token', models.CharField(blank=True, default='NONE', max_length=1000, null=True)),
                ('refresh_token', models.CharField(blank=True, default='NONE', max_length=1000, null=True)),
                ('realm_id', models.CharField(blank=True, default='NONE', max_length=1000, null=True)),
                ('auth_code', models.CharField(blank=True, default='NONE', max_length=1000, null=True)),
                ('state', models.CharField(blank=True, default='NONE', max_length=10, null=True)),
                ('refresh_token_expiry', models.CharField(blank=True, default='NONE', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Client Credentials',
                'verbose_name_plural': 'Client Credentials',
            },
            bases=('manager_efris.clientcredentials', 'oauth2.oauth2clientcredentials'),
        ),
    ]
