# Generated by Django 4.2.1 on 2023-06-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_quickbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbooksefrisclientcredentials',
            name='prod_url',
            field=models.CharField(blank=True, default='NONE', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='quickbooksefrisclientcredentials',
            name='sandbox_url',
            field=models.CharField(blank=True, default='NONE', max_length=1000, null=True),
        ),
    ]
