# Generated by Django 4.2.2 on 2023-07-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_quickbooks', '0002_quickbooksefrisclientcredentials_prod_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbooksefrisclientcredentials',
            name='basic_token',
            field=models.CharField(blank=True, default='NONE', max_length=1000, null=True),
        ),
    ]
