# Generated by Django 4.2.2 on 2023-07-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_quickbooks', '0004_alter_quickbooksefrisclientcredentials_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbooksefrisclientcredentials',
            name='cashier',
            field=models.CharField(blank=True, default='SYSTEM', max_length=100, null=True),
        ),
    ]
