# Generated by Django 4.2.1 on 2023-06-13 08:34

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EfrisInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(help_text='Instance id from app of origin', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingInvoice',
            fields=[
                ('origin_invoice_id', models.AutoField(help_text='Instance id from app of origin', primary_key=True, serialize=False)),
                ('app_of_origin', models.CharField(choices=[('DEAR', 'DEAR'), ('XERO', 'XERO'), ('GENERIC', 'GENERIC'), ('OTHER', 'OTHER')], default='GENERIC', max_length=100)),
                ('origin_request_data', jsonfield.fields.JSONField()),
                ('mita_request_data', jsonfield.fields.JSONField()),
                ('mita_response_data', jsonfield.fields.JSONField()),
                ('country_code', models.CharField(blank=True, choices=[('UG', 'UGANDA'), ('ZM', 'ZAMBIA'), ('BJ', 'BENIN')], default='UG', max_length=10, null=True)),
                ('mita_upload_code', models.CharField(blank=True, choices=[('200', 'SUCCESS'), ('400', 'ERROR')], default='400', max_length=10, null=True)),
                ('mita_upload_desc', models.CharField(blank=True, default='NONE', max_length=1000, null=True)),
                ('issue_date', models.DateField()),
                ('upload_date', models.DateField()),
                ('modified_date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('RECEIVED', 'RECEIVED'), ('SENDING', 'SENDING'), ('SENT', 'SENT'), ('ERROR', 'ERROR')], default='RECEIVED', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Outgoing Invoice',
                'verbose_name_plural': 'Incoming Invoices',
            },
        ),
    ]
