# Generated by Django 4.1 on 2022-09-24 14:40

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('efris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroEfrisClientCredentials',
            fields=[
                ('clientcredentials_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='efris.clientcredentials')),
                ('webhook_key', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=100)),
                ('callback_uri', models.CharField(max_length=150)),
                ('cred_state', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': ' Xero Efris Goods Configuration',
                'verbose_name_plural': ' Xero Efris Goods Configuration',
            },
            bases=('efris.clientcredentials',),
        ),
        migrations.CreateModel(
            name='XeroEfrisGoodsConfiguration',
            fields=[
                ('efrisgoodsconfiguration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='efris.efrisgoodsconfiguration')),
                ('xero_purchase_account', models.CharField(choices=[('300', 'PURCHASES')], default='300', max_length=10)),
                ('xero_tax_rate', models.CharField(choices=[('TAX004', 'EXEMPT'), ('TAX003', 'VAT')], default='TAX004', max_length=10)),
                ('client_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xero_api.xeroefrisclientcredentials')),
            ],
            options={
                'verbose_name': ' Xero Efris Goods Configuration',
                'verbose_name_plural': ' Xero Efris Goods Configuration',
            },
            bases=('efris.efrisgoodsconfiguration',),
        ),
        migrations.CreateModel(
            name='XeroEfrisGoodsAdjustment',
            fields=[
                ('efrisgoodsadjustment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='efris.efrisgoodsadjustment')),
                ('xero_invoice_type', models.CharField(choices=[('ACCPAY', 'INCREASE'), ('ACCREC', 'DECREASE')], default='ACCPAY', max_length=10)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xero_api.xeroefrisgoodsconfiguration')),
            ],
            options={
                'verbose_name': 'Xero Efris Goods Adjustment',
                'verbose_name_plural': 'Xero Efris Goods Adjustment',
            },
            bases=('efris.efrisgoodsadjustment',),
        ),
    ]
