# Generated by Django 4.1 on 2022-09-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xeroefrisclientcredentials',
            options={'verbose_name': ' Xero Efris Client Credentials', 'verbose_name_plural': 'Xero Efris Client Credentials'},
        ),
        migrations.AlterField(
            model_name='xeroefrisgoodsconfiguration',
            name='xero_tax_rate',
            field=models.CharField(choices=[('NONE', 'EXEMPT'), ('OUTPUT', 'VAT')], default='OUTPUT', max_length=10),
        ),
    ]
