# Generated by Django 4.1 on 2022-09-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_api', '0002_alter_xeroefrisclientcredentials_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xeroefrisgoodsconfiguration',
            name='xero_purchase_account',
        ),
        migrations.RemoveField(
            model_name='xeroefrisgoodsconfiguration',
            name='xero_tax_rate',
        ),
        migrations.AddField(
            model_name='xeroefrisclientcredentials',
            name='xero_exempt_tax_rate_code',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='xeroefrisclientcredentials',
            name='xero_purchase_account',
            field=models.CharField(default='300', max_length=10),
        ),
        migrations.AddField(
            model_name='xeroefrisclientcredentials',
            name='xero_standard_tax_rate_code',
            field=models.CharField(default='OUTPUT', max_length=10),
        ),
    ]
