# Generated by Django 4.1 on 2022-09-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_api', '0003_remove_xeroefrisgoodsconfiguration_xero_purchase_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeroefrisclientcredentials',
            name='xero_stock_in_contact_account',
            field=models.CharField(default='39efa556-8dda-4c81-83d3-a631e59eb6d3', max_length=100),
        ),
    ]
