# Generated by Django 4.1 on 2022-09-26 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_authorization', '0001_initial'),
        ('xero_api', '0005_alter_xeroefrisclientcredentials_xero_stock_in_contact_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xeroefrisclientcredentials',
            name='callback_uri',
        ),
        migrations.RemoveField(
            model_name='xeroefrisclientcredentials',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='xeroefrisclientcredentials',
            name='client_secret',
        ),
        migrations.RemoveField(
            model_name='xeroefrisclientcredentials',
            name='cred_state',
        ),
        migrations.RemoveField(
            model_name='xeroefrisclientcredentials',
            name='webhook_key',
        ),
        migrations.AddField(
            model_name='xeroefrisclientcredentials',
            name='oauth2clientcredentials_ptr',
            field=models.OneToOneField(auto_created=True, default='1', on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='client_authorization.oauth2clientcredentials'),
            preserve_default=False,
        ),
    ]
