# Generated by Django 4.1 on 2022-09-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xero_api', '0006_remove_xeroefrisclientcredentials_callback_uri_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xeroefrisclientcredentials',
            options={'verbose_name': 'Efris Client Credentials', 'verbose_name_plural': 'Efris Client Credentials'},
        ),
        migrations.AlterModelOptions(
            name='xeroefrisgoodsadjustment',
            options={'verbose_name': 'Efris Goods Adjustment', 'verbose_name_plural': 'Efris Goods Adjustment'},
        ),
        migrations.AlterModelOptions(
            name='xeroefrisgoodsconfiguration',
            options={'verbose_name': ' Efris Goods Configuration', 'verbose_name_plural': 'Efris Goods Configuration'},
        ),
    ]
