# Generated by Django 4.1 on 2022-10-03 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xero_api', '0007_alter_xeroefrisclientcredentials_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xeroefrisgoodsadjustment',
            name='good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xero_api.xeroefrisgoodsconfiguration'),
        ),
        migrations.AlterField(
            model_name='xeroefrisgoodsconfiguration',
            name='client_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xero_api.xeroefrisclientcredentials'),
        ),
    ]
