# Generated by Django 4.1 on 2022-09-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('tax_pin', models.CharField(max_length=30)),
                ('mita_api_header', models.CharField(max_length=150)),
                ('mita_country_code', models.CharField(choices=[('UG', 'UG'), ('ZM', 'ZM'), ('BN', 'BN')], default='UG', max_length=10)),
            ],
            options={
                'verbose_name': 'MiTa Credentials',
                'verbose_name_plural': 'MiTa Credentials',
            },
        ),
        migrations.CreateModel(
            name='EfrisGoodsAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.FloatField(help_text='Purchase Price')),
                ('supplier', models.CharField(help_text='Supplier', max_length=20)),
                ('supplier_tin', models.CharField(help_text='Supplier Tin', max_length=20)),
                ('quantity', models.CharField(help_text='Quantity', max_length=20)),
                ('currency', models.CharField(choices=[('102', 'USD'), ('101', 'UGX'), ('104', 'EUR')], default='101', max_length=10)),
                ('stock_in_type', models.CharField(choices=[('101', 'IMPORT'), ('102', 'LPO'), ('104', 'OPENING STOCK')], default='101', max_length=10)),
                ('adjust_type', models.CharField(blank=True, choices=[('', 'NONE'), ('101', 'EXPIRED'), ('102', 'DAMAGED'), ('104', 'OTHERS'), ('103', 'PERSONAL USES')], default='', max_length=10, null=True)),
                ('operation_type', models.CharField(choices=[('101', 'INCREASE INVENTORY'), ('102', 'DECREASE INVENTORY')], default='', max_length=10)),
                ('purchase_remarks', models.TextField(help_text='Purchase Remarks')),
            ],
            options={
                'verbose_name': 'Goods Stock In',
                'verbose_name_plural': 'Goods Stock In',
            },
        ),
        migrations.CreateModel(
            name='EfrisGoodsConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(help_text='Goods Name', max_length=20)),
                ('goods_code', models.CharField(help_text='Goods Code', max_length=20)),
                ('commodity_tax_category', models.CharField(choices=[('39111527', 'EXEMPT'), ('53103003', 'VAT')], default='39111527', max_length=10)),
                ('unit_price', models.FloatField(help_text='Unit Price')),
                ('currency', models.CharField(choices=[('102', 'USD'), ('101', 'UGX'), ('104', 'EUR')], default='101', max_length=10)),
                ('measure_unit', models.CharField(help_text='Measure Unit', max_length=20)),
                ('description', models.TextField(help_text='Description')),
            ],
            options={
                'verbose_name': ' Efris Goods Configuration',
                'verbose_name_plural': ' Efris Goods Configuration',
            },
        ),
    ]
