# Generated by Django 4.1 on 2022-09-25 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('efris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfrisCommodityCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efris_commodity_category_name', models.CharField(help_text='Efris Commodity Category', max_length=20)),
                ('efris_commodity_category_code', models.CharField(help_text='Efris Commodity Category Code', max_length=20)),
                ('tax_rate', models.FloatField(choices=[(0.0, 'EXEMPT'), (0.18, 'STANDARD')], default='', help_text='Currency Rate', max_length=10)),
            ],
            options={
                'verbose_name': 'Efris Commodity Category',
                'verbose_name_plural': 'Efris Commodity Categories',
            },
        ),
        migrations.CreateModel(
            name='EfrisCurrencyCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(help_text='Currency Name', max_length=20)),
                ('currency_code', models.CharField(help_text='Currency Code', max_length=20)),
                ('currency_abbr', models.CharField(help_text='Currency Abbr', max_length=20)),
            ],
            options={
                'verbose_name': 'Efris Currency Code',
                'verbose_name_plural': 'Efris Currency Codes',
            },
        ),
        migrations.AlterField(
            model_name='efrisgoodsadjustment',
            name='adjust_type',
            field=models.CharField(blank=True, choices=[('', 'NONE'), ('101', 'EXPIRED'), ('102', 'DAMAGED'), ('104', 'OTHERS'), ('103', 'PERSONAL USES'), ('105', 'RAW MATERIALS')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='efrisgoodsadjustment',
            name='stock_in_type',
            field=models.CharField(choices=[('101', 'IMPORT'), ('102', 'LPO'), ('103', 'MANUFACTURING/ASSEMBLY'), ('104', 'OPENING STOCK')], default='101', max_length=10),
        ),
        migrations.AlterField(
            model_name='efrisgoodsadjustment',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efris.efriscurrencycodes'),
        ),
        migrations.AlterField(
            model_name='efrisgoodsconfiguration',
            name='commodity_tax_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efris.efriscommoditycategories'),
        ),
        migrations.AlterField(
            model_name='efrisgoodsconfiguration',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efris.efriscurrencycodes'),
        ),
    ]
