# Generated by Django 4.1 on 2022-09-25 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('efris', '0002_efriscommoditycategories_efriscurrencycodes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfrisMeasureUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_unit_name', models.CharField(help_text='Measure Unit Name', max_length=20)),
                ('measure_unit_code', models.CharField(help_text='Measure Unit Code', max_length=20)),
                ('measure_unit_abbr', models.CharField(blank=True, help_text='Measure Unit Abbr', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Efris Measure Unit',
                'verbose_name_plural': 'Efris Measure Units',
            },
        ),
        migrations.AlterField(
            model_name='efrisgoodsconfiguration',
            name='commodity_tax_category',
            field=models.ForeignKey(help_text='Efris Commodity Category', on_delete=django.db.models.deletion.CASCADE, to='efris.efriscommoditycategories'),
        ),
        migrations.AlterField(
            model_name='efrisgoodsconfiguration',
            name='currency',
            field=models.ForeignKey(help_text='Currency', on_delete=django.db.models.deletion.CASCADE, to='efris.efriscurrencycodes'),
        ),
        migrations.AlterField(
            model_name='efrisgoodsconfiguration',
            name='measure_unit',
            field=models.ForeignKey(help_text='Measure Unit', on_delete=django.db.models.deletion.CASCADE, to='efris.efrismeasureunits'),
        ),
    ]
