# Generated by Django 4.1 on 2022-09-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efris', '0003_efrismeasureunits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efriscommoditycategories',
            name='tax_rate',
            field=models.FloatField(choices=[(0.0, 'EXEMPT'), (0.18, 'STANDARD')], default=0.18, help_text='Currency Rate', max_length=10),
        ),
    ]
