# Generated by Django 4.1 on 2022-10-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efris', '0004_alter_efriscommoditycategories_tax_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcredentials',
            options={'verbose_name': 'MiTa Credentialsk', 'verbose_name_plural': 'MiTa Credentials'},
        ),
    ]
