# Generated by Django 4.1 on 2022-10-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efris', '0005_alter_clientcredentials_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efrisgoodsadjustment',
            name='stock_in_type',
            field=models.CharField(blank=True, choices=[('', 'NONE'), ('101', 'IMPORT'), ('102', 'LPO'), ('103', 'MANUFACTURING/ASSEMBLY'), ('104', 'OPENING STOCK')], default='101', max_length=10, null=True),
        ),
    ]
