# Generated by Django 4.1 on 2022-10-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efris', '0006_alter_efrisgoodsadjustment_stock_in_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efrisgoodsadjustment',
            name='supplier_tin',
            field=models.CharField(blank=True, help_text='Supplier Tin', max_length=20, null=True),
        ),
    ]
