# Generated by Django 4.1 on 2022-10-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efris', '0007_alter_efrisgoodsadjustment_supplier_tin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efrisgoodsadjustment',
            name='supplier',
            field=models.CharField(blank=True, help_text='Supplier', max_length=20, null=True),
        ),
    ]
