# Generated by Django 4.2.1 on 2023-05-24 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth2', '0001_initial'),
        ('manager_efris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroEfrisClientCredentials',
            fields=[
                ('oauth2clientcredentials_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='oauth2.oauth2clientcredentials')),
                ('clientcredentials_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager_efris.clientcredentials')),
                ('xero_purchase_account', models.CharField(default='300', max_length=10)),
                ('xero_stock_in_contact_account', models.CharField(default='39efa556-8dda-4c81-83d3-a631e59eb6d3', max_length=255)),
                ('xero_exempt_tax_rate_code', models.CharField(default='NONE', max_length=10)),
                ('xero_standard_tax_rate_code', models.CharField(default='OUTPUT', max_length=10)),
            ],
            options={
                'verbose_name': 'Client Credentials',
                'verbose_name_plural': 'Client Credentials',
            },
            bases=('manager_efris.clientcredentials', 'oauth2.oauth2clientcredentials'),
        ),
        migrations.CreateModel(
            name='XeroEfrisGoodsConfiguration',
            fields=[
                ('efrisgoodsconfiguration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager_efris.efrisgoodsconfiguration')),
                ('client_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_xero.xeroefrisclientcredentials')),
            ],
            options={
                'verbose_name': 'Goods Configuration',
                'verbose_name_plural': 'Goods Configuration',
            },
            bases=('manager_efris.efrisgoodsconfiguration',),
        ),
        migrations.CreateModel(
            name='XeroEfrisGoodsAdjustment',
            fields=[
                ('efrisgoodsadjustment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager_efris.efrisgoodsadjustment')),
                ('xero_invoice_type', models.CharField(choices=[('ACCPAY', 'INCREASE'), ('ACCREC', 'DECREASE')], default='ACCPAY', max_length=10)),
                ('good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_xero.xeroefrisgoodsconfiguration')),
            ],
            options={
                'verbose_name': 'Goods Adjustment',
                'verbose_name_plural': 'Goods Adjustment',
            },
            bases=('manager_efris.efrisgoodsadjustment',),
        ),
    ]
